# Generated by Django 5.2.4 on 2025-12-26 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('bio', models.TextField(blank=True, help_text='Short bio about yourself')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('membership_type', models.CharField(choices=[('regular', 'Regular Member'), ('active', 'Active Member'), ('executive', 'Executive Member')], default='regular', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='main.memberprofile')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('member', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ProgramParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('volunteer', 'Volunteer'), ('coordinator', 'Coordinator'), ('lead', 'Program Lead')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_participations', to='main.memberprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='main.program')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('member', 'program')},
            },
        ),
    ]
