# Generated by Django 5.2.4 on 2026-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_memberprofile_eventattendance_programparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Your blood group', max_length=3),
        ),
    ]
