# Generated by Django 5.2.4 on 2026-01-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_heroimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroImage',
        ),
    ]
